#!/bin/sh

case "$1" in
	start|"")
		echo Penglai Enclave Start
		echo -------------------------------------------------------

		if [ -x /root/host ] && [ -x /root/prime ]; then
			/root/host /root/prime
		fi
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
