obj-m += penglai.o
ccflags-y += -fno-asynchronous-unwind-tables -fno-unwind-tables

penglai-objs := \
	penglai-enclave-driver.o \
	penglai-enclave-elfloader.o \
	penglai-enclave-page.o \
	penglai-enclave.o \
	penglai-enclave-ioctl.o
